// G. levels: the zones and the campaign, in play order. This file is the source of truth.
// Edit here, or in the in-game editor and use "Copy levels.js" / "Download levels.js" to replace this file.
// tools/campaign.mjs rebuilds it from specs and recipes. Key codes are physical (KeyboardEvent.code); see README.md.
window.GDOT_ZONES=[
 {"id":"hatchery","name":"Hatchery","env":"kelp","keys":["KeyL","Digit9","KeyP","Digit0","Slash"],"tutorial":true,"rules":"territory"},
 {"id":"shallows","name":"Shallows","env":"sand","keys":["KeyG","KeyH","KeyF","KeyJ","KeyD","KeyK","KeyS","KeyA"],"rules":"territory"},
 {"id":"rock-garden","name":"Rock garden","env":"stone","keys":["KeyT","KeyY","KeyR","KeyU","KeyE","KeyI","KeyW","KeyQ"]},
 {"id":"currents","name":"Currents","env":"blue","keys":["Digit5","Digit6","Digit4","Digit7","Digit3","Digit8","Digit2","Digit1"]},
 {"id":"caves","name":"Caves","env":"dark","keys":["KeyB","KeyN","KeyV","KeyM","KeyC","Comma","KeyX","KeyZ"]},
 {"id":"the-rim","name":"The rim","env":"deep","keys":["Tab","CapsLock","Space","ControlLeft","Escape","Enter","F1","F4"]}
];
window.GDOT_LEVELS=[
 {"id":"fill","name":"Fill","goal":8,"start":["KeyL"],"required":[],"coach":{"1":"It stays there. Tap {K} to put down the next one.","2":"Each {tentacle} uncovers the keys next to it. Tap {J}.","3":"The tray counts to {goal}: every key in the tank. Find the rest.","4":"One more key fills the tray. Find it.","letgo":"{G.} tries again.","fog":"{fog} Fog: only keys next to a {tentacle} are open.","algae":"{algae} Algae: nothing to grip, and not yours to fill.","reach":"Only keys next to a {tentacle}, or the one you just lifted.","ready":"{Hold} {L} to put down your first {tentacle}. {hold}","start":"Your first {tentacle} goes on {L}, the pulsing key.","lift":"Tapping a {tentacle} lifts it. Tap it again to put it back.","won":"Every key is yours: clear! Par, top right, is the fewest presses."},"tank":["KeyL","KeyK","KeyJ","Semicolon","Quote"],"par":5,"zone":"hatchery",
  "terrain":{"KeyO":"algae","KeyP":"algae","Comma":"algae","Period":"algae","KeyI":"algae","KeyM":"algae","KeyU":"algae","KeyH":"algae","KeyN":"algae","BracketLeft":"algae","Slash":"algae","BracketRight":"algae","Enter":"algae","ShiftRight":"algae"},
  "creatures":[]},
 {"id":"taken","name":"Taken","goal":8,"start":["Digit9"],"required":[],"coach":{"1":"A {shark}! Its arrow shows its next key. Tap {0}: it swims off first.","2":"Now its arrow points at your {tentacle} on {~0}. Let it: tap {-}.","3":"{~0} is the {shark}'s while it sits there. Tap {=}.","4":"The {shark} left: {0} is free again. Fill it.","letgo":"{G.} tries again.","fog":"{fog} Fog: only keys next to a {tentacle} are open.","algae":"{algae} Algae: nothing to grip, and not yours to fill.","reach":"Only keys next to a {tentacle}, or the one you just lifted.","overrun":"Every {tentacle} was taken, so the tank starts over. {G.} tries again.","ready":"Each tank starts on its own key. {Hold} {9}. {hold}","start":"This tank starts on {9}, the pulsing key.","taken":"Taken! A creature takes the key, never your life.","lift":"Tapping a {tentacle} lifts it. Tap it again to put it back.","won":"Clear! A taken key is only a key to fill again."},"tank":["Digit9","Digit0","Minus","Equal"],"par":5,"zone":"hatchery",
  "terrain":{"F7":"algae","F8":"algae","Digit8":"algae","KeyI":"algae","KeyO":"algae","KeyP":"algae","F9":"algae","BracketLeft":"algae","F10":"algae","Backspace":"algae","BracketRight":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyO","Digit0","KeyP","BracketLeft"],"loop":"pingpong","pathIndex":5,"at":"KeyO"}]},
 {"id":"wait","name":"Wait","goal":8,"start":["KeyP"],"required":[],"coach":{"1":"Tap {;} and see what swims here.","2":"Its arrow is on {~'}, your only open key. Wait: tap {;} to lift it.","3":"That wait cost one press. Now tap {'}: the {shark} swims off first.","letgo":"Keep another key held while you tap one. {G.} tries again.","fog":"{fog} Fog: only keys next to a {tentacle} are open.","algae":"{algae} Algae: nothing to grip, and not yours to fill.","reach":"Only keys next to a {tentacle}, or the one you just lifted.","overrun":"Every {tentacle} was taken, so the tank starts over. {G.} tries again.","ready":"Each tank starts on its own key. {Hold} {P}. {hold}","start":"This tank starts on {P}, the pulsing key.","lift":"Lifting is free: nothing moves. Tap it again to put it back: a wait.","taken":"Taken: that press only waited. The key is free once it leaves.","won":"Clear, with the {shark} on {~]}: a creature's key counts as its own."},"tank":["KeyP","Semicolon","Quote","BracketRight"],"par":4,"zone":"hatchery",
  "terrain":{"Digit0":"algae","Minus":"algae","KeyO":"algae","BracketLeft":"algae","KeyL":"algae","Period":"algae","Slash":"algae","Enter":"algae","ShiftRight":"algae","Equal":"algae","Backspace":"algae","Backslash":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["BracketRight","Quote","Slash"],"loop":"pingpong","pathIndex":2,"at":"BracketRight"}]},
 {"id":"its-own","name":"Its own","goal":8,"start":["Digit0"],"required":[],"coach":{"1":"Tap {-} and see what swims here.","2":"It always sits on {~[} or {~=}. Leave those for last: tap {P}.","3":"Now take {=} as it leaves. The key it lands on counts as its own.","letgo":"{G.} tries again.","fog":"{fog} Fog: only keys next to a {tentacle} are open.","algae":"{algae} Algae: nothing to grip, and not yours to fill.","reach":"Only keys next to a {tentacle}, or the one you just lifted.","overrun":"Every {tentacle} was taken, so the tank starts over. {G.} tries again.","ready":"Each tank starts on its own key. {Hold} {0}. {hold}","start":"This tank starts on {0}, the pulsing key.","taken":"Taken: it keeps coming back. Leave {~[} and {~=} for last.","lift":"Tapping a {tentacle} lifts it. Tap it again to put it back: a wait.","won":"Clear with {~[} unfilled: you let the {shark} hold it."},"tank":["Digit0","Minus","KeyP","Equal","BracketLeft"],"par":4,"zone":"hatchery",
  "terrain":{"F8":"algae","Digit9":"algae","KeyO":"algae","F9":"algae","KeyL":"algae","Semicolon":"algae","F10":"algae","Backspace":"algae","BracketRight":"algae","Quote":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["Equal","BracketLeft"],"loop":"pingpong","pathIndex":1,"at":"Equal"}]},
 {"id":"starfish","name":"Starfish","goal":8,"start":["Slash"],"required":["BracketLeft"],"coach":{"1":"Tap {'} and look around.","2":"A {starfish}! Tap {[} and watch the {algae} around it.","3":"Par is {par}. Fill the new keys, and let the {shark} hold one.","letgo":"{G.} tries again.","fog":"{fog} Fog: only keys next to a {tentacle} are open.","algae":"{algae} Algae: nothing to grip, and not yours to fill.","reach":"Only keys next to a {tentacle}, or the one you just lifted.","overrun":"Every {tentacle} was taken, so the tank starts over. {G.} tries again.","ready":"Each tank starts on its own key. {Hold} {/}. {hold}","start":"This tank starts on {/}, the pulsing key.","grow":"The {starfish} turned the algae around it into water: more to fill.","taken":"Taken: it comes back to {~]} every other press. Leave that key to it.","lift":"Tapping a {tentacle} lifts it. Tap it again to put it back: a wait.","won":"Clear! Every tank has a par now. {G.} goes to the Shallows. {next}"},"tank":["Slash","Quote","BracketLeft"],"par":7,"zone":"hatchery",
  "terrain":{"Semicolon":"algae","Period":"algae","ShiftRight":"algae","MetaRight":"algae","BracketRight":"algae","Enter":"algae","Minus":"algae","Equal":"algae","KeyP":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["BracketRight","Enter"],"loop":"pingpong","pathIndex":1,"at":"BracketRight"}]},
 {"id":"pacing","name":"Pacing","goal":8,"start":["KeyG"],"required":[],"tank":["KeyG","KeyB","KeyH","KeyY","KeyT","KeyR"],"par":6,"zone":"shallows",
  "terrain":{"KeyF":"algae","KeyV":"algae","KeyN":"algae","Space":"algae","KeyU":"algae","KeyJ":"algae","Digit6":"algae","Digit7":"algae","Digit5":"algae","Digit4":"algae","KeyE":"algae","KeyD":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyR","KeyT","KeyY"],"loop":"pingpong","pathIndex":2,"at":"KeyR"}]},
 {"id":"round-trip","name":"Round trip","goal":8,"start":["KeyH"],"required":[],"tank":["KeyH","KeyU","KeyI","KeyY","KeyB","KeyK","KeyN"],"par":7,"zone":"shallows",
  "terrain":{"KeyG":"algae","KeyJ":"algae","Digit7":"algae","Digit8":"algae","Digit9":"algae","KeyO":"algae","Digit6":"algae","KeyT":"algae","KeyV":"algae","Space":"algae","KeyL":"algae","KeyM":"algae","Comma":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyI","KeyU","KeyJ","KeyN"],"loop":"pingpong","pathIndex":3,"at":"KeyI"}]},
 {"id":"slow-crab","name":"Slow crab","goal":8,"start":["KeyF"],"required":[],"tank":["KeyF","KeyT","Digit7","Digit8","Digit9","KeyY","Digit6"],"par":8,"zone":"shallows",
  "terrain":{"Digit6":"rock","KeyR":"algae","KeyD":"algae","KeyG":"algae","KeyC":"algae","KeyV":"algae","Digit5":"algae","F5":"algae","F6":"algae","KeyU":"algae","F7":"algae","KeyI":"algae","F8":"algae","Digit0":"algae","KeyO":"algae","KeyH":"algae"},
  "creatures":[{"type":"crab","mover":"dir","dir":"SW","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"Digit7","path":[],"loop":"pingpong","pathIndex":0}]},
 {"id":"urchin","name":"Urchin","goal":8,"start":["KeyJ"],"required":[],"tank":["KeyJ","KeyK","KeyI","KeyM","KeyL","KeyO","Digit0","Digit9","KeyP"],"par":7,"zone":"shallows",
  "terrain":{"KeyU":"algae","KeyH":"algae","KeyN":"algae","Comma":"algae","Digit8":"algae","Space":"algae","Semicolon":"algae","Period":"algae","F8":"algae","Minus":"algae","F7":"algae","BracketLeft":"algae"},
  "creatures":[{"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":false,"wake":false,"at":"KeyO","path":[],"loop":"pingpong","pathIndex":0},
    {"type":"crab","mover":"dir","dir":"SE","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"Digit9","path":[],"loop":"pingpong","pathIndex":0}]},
 {"id":"fish-supper","name":"Fish supper","goal":8,"start":["KeyD"],"required":[],"tank":["KeyD","KeyX","KeyZ","KeyE","KeyS","KeyR","Digit4","Digit5","KeyA"],"par":9,"zone":"shallows",
  "terrain":{"KeyF":"algae","KeyC":"algae","AltLeft":"algae","Space":"algae","ShiftLeft":"algae","MetaLeft":"algae","Digit3":"algae","KeyW":"algae","KeyT":"algae","F3":"algae","F4":"algae","Digit6":"algae","KeyQ":"algae","CapsLock":"algae","KeyG":"algae","KeyV":"algae","KeyB":"algae","KeyN":"algae","KeyM":"algae","Comma":"algae","AltRight":"algae","ControlLeft":"algae","F2":"algae","Digit2":"algae","KeyY":"algae","F5":"algae","Digit7":"algae","Digit1":"algae","Tab":"algae"},
  "creatures":[{"type":"fish","mover":"flee","dir":"E","speed":0.5,"size":"small","prey":true,"cave":false,"wake":false,"at":"KeyZ","path":[],"loop":"pingpong","pathIndex":0},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyA","KeyZ","KeyS","KeyX"],"loop":"pingpong","pathIndex":3,"at":"KeyA"}]},
 {"id":"two-sharks","name":"Two sharks","goal":8,"start":["KeyK"],"required":[],"tank":["KeyK","KeyM","KeyL","KeyI","KeyU","KeyO","KeyP","KeyY","KeyJ"],"par":9,"zone":"shallows",
  "terrain":{"Comma":"algae","KeyN":"algae","Space":"algae","Semicolon":"algae","Period":"algae","Digit8":"algae","Digit9":"algae","Digit7":"algae","KeyH":"algae","Digit0":"algae","Minus":"algae","BracketLeft":"algae","Digit6":"algae","KeyT":"algae","KeyG":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyU","KeyJ","KeyM","KeyN","KeyH"],"loop":"pingpong","pathIndex":2,"at":"KeyU"},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyU","KeyY","Digit6"],"loop":"pingpong","pathIndex":2,"at":"KeyU"}]},
 {"id":"sleeping-eel","name":"Sleeping eel","goal":8,"start":["KeyS"],"required":[],"tank":["KeyS","KeyW","KeyQ","Digit1","Digit2","KeyA","KeyZ","KeyX","KeyE"],"par":8,"zone":"shallows",
  "terrain":{"KeyD":"algae","Digit3":"algae","Tab":"algae","CapsLock":"algae","Backquote":"algae","F1":"algae","ShiftLeft":"algae","MetaLeft":"algae","AltLeft":"algae","KeyC":"algae","Space":"algae","Digit4":"algae","KeyR":"algae"},
  "creatures":[{"type":"eel","mover":"chase","dir":"E","speed":1,"size":"big","prey":false,"cave":true,"wake":true,"at":"Digit1","path":[],"loop":"pingpong","pathIndex":0},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["Digit2","Digit1","KeyQ"],"loop":"pingpong","pathIndex":0,"at":"Digit2"}]},
 {"id":"growth","name":"Growth","goal":8,"start":["KeyA"],"required":["KeyE"],"tank":["KeyA","KeyW","KeyQ","Digit1","KeyE","KeyD","Digit2","KeyR","Digit4"],"par":11,"zone":"shallows",
  "terrain":{"CapsLock":"algae","KeyS":"algae","ShiftLeft":"algae","KeyZ":"algae","Digit3":"algae","Tab":"algae","Backquote":"algae","KeyF":"algae","KeyX":"algae","KeyC":"algae","F1":"algae","Digit5":"algae","KeyT":"algae","F3":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["Digit4","KeyR","KeyE","KeyD"],"loop":"pingpong","pathIndex":0,"at":"Digit4"},
    {"type":"crab","mover":"dir","dir":"E","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyD","path":[],"loop":"pingpong","pathIndex":0}]},
 {"id":"barracuda","name":"Barracuda","goal":7,"start":["KeyT"],"required":[],"zone":"rock-garden",
  "terrain":{"Digit6":"algae","KeyY":"algae","KeyE":"algae","KeyV":"algae","AltLeft":"algae","Space":"algae","F3":"algae","KeyA":"algae","ShiftLeft":"algae","MetaLeft":"algae","KeyH":"algae","KeyB":"algae","Digit2":"algae","KeyQ":"algae","F2":"algae","F4":"algae","KeyZ":"rock","Digit3":"rock"},
  "creatures":[{"type":"barracuda","mover":"dir","dir":"NW","speed":2,"size":"small","prey":false,"cave":false,"wake":false,"at":"Digit4"}]},
 {"id":"crab-lunch","name":"Crab lunch","goal":5,"start":["KeyY"],"required":["Digit5"],"zone":"rock-garden",
  "terrain":{"Digit3":"rock","Digit7":"rock","F3":"algae","KeyE":"algae","F4":"algae","F5":"algae","KeyD":"algae","KeyF":"algae","KeyG":"algae","KeyU":"algae","KeyH":"algae"},
  "creatures":[{"type":"crab","mover":"dir","dir":"W","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"Digit6","path":[],"loop":"pingpong","pathIndex":0},
    {"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":false,"wake":false,"at":"Digit5","path":[],"loop":"pingpong","pathIndex":0}]},
 {"id":"chum","name":"Chum","goal":7,"start":["KeyR"],"required":[],"zone":"rock-garden",
  "terrain":{"Digit5":"algae","KeyD":"algae","KeyW":"algae","KeyS":"algae","KeyG":"algae","F5":"algae","Digit7":"algae","F3":"algae","KeyH":"algae","F2":"algae","Digit2":"algae","Space":"algae","KeyX":"algae","KeyN":"algae","Digit8":"algae","KeyI":"algae","KeyJ":"algae","F4":"algae","KeyQ":"algae","KeyA":"algae","KeyZ":"algae","F6":"algae","F1":"algae","Digit1":"algae","KeyM":"algae","Comma":"algae","AltLeft":"algae","AltRight":"algae","F7":"algae","Digit9":"algae","KeyO":"algae","KeyK":"algae"},
  "creatures":[{"type":"fish","mover":"flee","dir":"E","speed":0.5,"size":"small","prey":true,"cave":false,"wake":false,"at":"KeyV"},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyY","Digit6","KeyT","KeyR","KeyE"],"loop":"loop","pathIndex":1}]},
 {"id":"tide-pool","name":"Tide pool","goal":8,"start":["KeyU"],"required":[],"zone":"rock-garden",
  "terrain":{"KeyI":"algae","KeyJ":"algae","F5":"algae","F6":"algae","Digit5":"algae","KeyR":"algae","KeyC":"algae","KeyV":"algae","KeyB":"algae","KeyN":"algae","F7":"algae","Digit9":"algae","KeyE":"algae","KeyS":"algae","KeyX":"algae"},
  "creatures":[{"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":false,"wake":false,"at":"Digit6"},
    {"type":"crab","mover":"dir","dir":"E","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyG"}]},
 {"id":"corridor","name":"Corridor","goal":7,"start":["KeyE"],"required":["KeyV"],"zone":"rock-garden",
  "terrain":{"F2":"algae","KeyT":"algae","F4":"algae","KeyA":"algae","KeyX":"algae","KeyC":"algae","Tab":"algae","CapsLock":"algae","KeyB":"algae","Space":"algae","ShiftLeft":"algae","MetaLeft":"algae","AltLeft":"algae","F1":"algae","Backquote":"algae","F3":"algae","KeyY":"algae","KeyH":"algae","F5":"algae","Digit7":"algae","KeyQ":"rock","Digit1":"rock","Digit2":"rock","Digit6":"rock","KeyZ":"rock"},
  "creatures":[{"type":"barracuda","mover":"dir","dir":"NW","speed":2,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyV"}]},
 {"id":"boulders","name":"Boulders","goal":7,"start":["KeyI"],"required":[],"zone":"rock-garden",
  "terrain":{"KeyK":"algae","F6":"algae","F7":"algae","KeyH":"algae","KeyN":"algae","KeyY":"algae","Digit0":"algae","KeyL":"algae","Comma":"algae","Space":"algae","F5":"algae","F8":"algae","Digit5":"algae","Semicolon":"algae","F9":"algae","Equal":"algae","BracketRight":"algae","Quote":"algae","KeyR":"algae","KeyF":"algae","KeyG":"algae","Minus":"rock","Digit6":"rock","BracketLeft":"rock","KeyT":"rock"},
  "creatures":[{"type":"shark","mover":"dir","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"at":"KeyM"},
    {"type":"crab","mover":"dir","dir":"NW","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"Digit7"}]},
 {"id":"pinball","name":"Pinball","goal":7,"start":["KeyW"],"required":[],"zone":"rock-garden",
  "terrain":{"F2":"algae","CapsLock":"algae","ShiftLeft":"algae","KeyZ":"algae","F3":"algae","Digit5":"algae","KeyX":"algae","Tab":"algae","Space":"algae","KeyG":"algae","KeyB":"algae","F1":"algae","Digit6":"algae","KeyY":"algae","Backquote":"algae","KeyR":"rock","KeyC":"rock","KeyF":"rock","Digit4":"rock"},
  "creatures":[{"type":"shark","mover":"dir","dir":"NW","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"at":"Digit1"},
    {"type":"barracuda","mover":"dir","dir":"SW","speed":2,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyV"}]},
 {"id":"crossing","name":"Crossing","goal":7,"start":["KeyQ"],"required":["Digit5"],"zone":"rock-garden",
  "terrain":{"Tab":"algae","CapsLock":"algae","KeyS":"algae","F1":"algae","KeyR":"algae","KeyD":"algae","Escape":"algae","ShiftLeft":"algae","F2":"algae","MetaLeft":"algae","AltLeft":"algae","F3":"algae","F4":"algae","Digit6":"algae","KeyT":"algae","KeyC":"algae","Space":"algae"},
  "creatures":[{"type":"crab","mover":"dir","dir":"E","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyE"},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["Backquote","Digit1","KeyQ"],"loop":"loop","pathIndex":0}]},
 {"id":"lift","name":"Lift","goal":6,"start":["Digit5"],"required":[],"zone":"currents",
  "terrain":{"F4":"algae","KeyT":"algae","F3":"algae","KeyE":"algae","KeyD":"algae","KeyC":"algae","KeyV":"algae","KeyY":"algae","F2":"algae","Digit2":"algae","KeyW":"algae","Space":"algae","KeyU":"algae","KeyJ":"algae","F5":"algae","Digit7":"algae","KeyM":"algae"},
  "creatures":[{"type":"crab","mover":"dir","dir":"NW","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyF"}]},
 {"id":"retreat","name":"Retreat","goal":7,"start":["Digit6"],"required":[],"zone":"currents",
  "terrain":{"F5":"algae","Digit5":"algae","Digit7":"algae","Digit8":"algae","KeyJ":"algae","Digit9":"algae","KeyO":"algae","KeyB":"algae","Space":"algae","KeyC":"algae","Comma":"algae","KeyL":"algae","KeyR":"algae","KeyD":"algae","KeyI":"rock"},
  "creatures":[{"type":"crab","mover":"dir","dir":"NE","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyT"},
    {"type":"crab","mover":"dir","dir":"W","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyM"}]},
 {"id":"walker","name":"Walker","goal":2,"start":["Digit4"],"required":["Digit0"],"maxTentacles":2,"lift":"one","zone":"currents",
  "terrain":{"F3":"algae","Digit3":"algae","KeyE":"algae","KeyR":"algae","F4":"algae","KeyT":"algae","F5":"algae","KeyY":"algae","F6":"algae","KeyU":"algae","F7":"algae","KeyI":"algae","F8":"algae","KeyO":"algae","Minus":"algae","KeyP":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["F7","Digit8","KeyI"],"loop":"pingpong","pathIndex":0,"at":"F7"}]},
 {"id":"relocate","name":"Relocate","goal":7,"start":["Digit7"],"required":[],"zone":"currents",
  "terrain":{"F5":"algae","F6":"algae","KeyY":"algae","F7":"algae","F8":"algae","KeyM":"algae","KeyP":"algae","Slash":"algae","AltRight":"algae","KeyG":"algae","BracketLeft":"algae","Minus":"algae","Space":"algae","KeyV":"algae","Digit5":"algae","KeyT":"algae","BracketRight":"algae","Enter":"algae","ShiftRight":"algae","KeyJ":"rock","KeyH":"rock","Period":"rock","KeyL":"rock"},
  "creatures":[{"type":"eel","mover":"chase","dir":"E","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"at":"Digit0"},
    {"type":"crab","mover":"dir","dir":"W","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyO"}]},
 {"id":"bait","name":"Bait","goal":7,"start":["Digit3"],"required":[],"zone":"currents",
  "terrain":{"F2":"algae","KeyS":"algae","KeyD":"algae","Digit5":"algae","KeyC":"algae","Space":"algae","Digit6":"algae","KeyY":"algae","KeyQ":"algae","KeyH":"algae","CapsLock":"algae","ShiftLeft":"algae","KeyN":"algae","F3":"algae","KeyX":"algae","MetaLeft":"algae","AltLeft":"algae","F1":"algae","Digit1":"algae","KeyV":"rock","KeyG":"rock"},
  "creatures":[{"type":"eel","mover":"chase","dir":"E","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"at":"KeyF"},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyR","KeyE","Digit3","KeyW"],"loop":"loop","pathIndex":3}]},
 {"id":"anchor","name":"Anchor","goal":8,"start":["Digit8"],"required":["Quote"],"zone":"currents",
  "terrain":{"F6":"algae","F7":"algae","F8":"algae","Minus":"algae","KeyJ":"algae","KeyK":"algae","F5":"algae","KeyL":"algae","Equal":"algae","KeyT":"algae","KeyH":"algae","Digit5":"algae","Backspace":"algae","Backslash":"algae","Enter":"algae","KeyF":"algae","KeyV":"algae","KeyB":"algae","Slash":"algae","ShiftRight":"algae","Period":"algae","Digit0":"rock","Digit6":"rock","BracketRight":"rock","KeyP":"reef"},
  "creatures":[{"type":"barracuda","mover":"dir","dir":"W","speed":2,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyP"},
    {"type":"crab","mover":"dir","dir":"NW","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyY"}]},
 {"id":"barracuda-lane","name":"Barracuda lane","goal":8,"start":["Digit2"],"required":["KeyF"],"zone":"currents",
  "terrain":{"F1":"algae","Tab":"algae","CapsLock":"algae","F2":"algae","ShiftLeft":"algae","KeyZ":"algae","KeyR":"algae","KeyC":"algae","AltLeft":"algae","Space":"algae","Backquote":"algae","KeyT":"algae","KeyG":"algae","F3":"algae","F4":"algae","Digit6":"algae","KeyB":"algae","Digit4":"rock","KeyA":"rock"},
  "creatures":[{"type":"barracuda","mover":"dir","dir":"NW","speed":2,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyF"},
    {"type":"crab","mover":"dir","dir":"W","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyV"}]},
 {"id":"three-marks","name":"Three marks","goal":8,"start":["Digit1"],"required":["KeyS","KeyF","KeyD"],"zone":"currents",
  "terrain":{"Tab":"algae","CapsLock":"algae","F1":"algae","ShiftLeft":"algae","F2":"algae","Digit4":"algae","Escape":"algae","AltLeft":"algae","Space":"algae","KeyT":"algae","KeyG":"algae","MetaLeft":"algae","KeyH":"algae","KeyN":"algae","Digit5":"algae","KeyE":"rock","KeyB":"rock"},
  "creatures":[{"type":"crab","mover":"dir","dir":"NE","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyS"},
    {"type":"barracuda","mover":"dir","dir":"W","speed":2,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyX"},
    {"type":"shark","mover":"dir","dir":"E","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"at":"Digit3"}]},
 {"id":"the-cave","name":"The cave","goal":7,"start":["KeyB"],"required":[],"zone":"caves",
  "terrain":{"KeyG":"algae","KeyN":"algae","Space":"algae","KeyU":"algae","KeyK":"algae","KeyM":"algae","Digit8":"algae","Digit9":"algae","Digit0":"algae","KeyP":"algae","KeyL":"algae","KeyX":"algae","Digit7":"algae","KeyE":"algae","KeyR":"algae","KeyS":"algae","F5":"algae","F4":"algae","Digit4":"algae","KeyC":"cave","KeyJ":"cave","KeyT":"reef"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyI","KeyJ","KeyH","KeyY"],"loop":"loop","pathIndex":0},
    {"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":false,"wake":false,"at":"KeyT"}]},
 {"id":"something-stirred","name":"Something stirred","goal":7,"start":["KeyN"],"required":[],"zone":"caves",
  "terrain":{"KeyM":"algae","Space":"algae","KeyG":"algae","KeyU":"algae","KeyO":"algae","KeyF":"algae","F6":"algae","F7":"algae","Digit7":"algae","Digit6":"algae","KeyD":"algae","KeyX":"algae","Digit5":"algae","KeyR":"algae","KeyL":"algae","Comma":"algae","F8":"algae","Digit0":"algae","KeyT":"cave"},
  "creatures":[{"type":"eel","mover":"chase","dir":"E","speed":1,"size":"big","prey":false,"cave":true,"wake":true,"at":"KeyT"},
    {"type":"crab","mover":"dir","dir":"NE","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"Digit8"}]},
 {"id":"two-mouths","name":"Two mouths","goal":7,"start":["KeyV"],"required":[],"zone":"caves",
  "terrain":{"KeyG":"algae","Space":"algae","KeyX":"algae","Digit5":"algae","KeyY":"algae","KeyS":"algae","KeyN":"algae","F2":"algae","Digit2":"algae","F5":"algae","KeyQ":"algae","KeyA":"algae","F3":"algae","KeyU":"algae","KeyJ":"algae","F6":"algae","Digit8":"algae","Digit7":"cave","KeyW":"cave"},
  "creatures":[{"type":"eel","mover":"chase","dir":"E","speed":1,"size":"big","prey":false,"cave":true,"wake":true,"at":"Digit7"},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyR","KeyD","KeyE"],"loop":"loop","pathIndex":0}]},
 {"id":"shark-bait","name":"Shark bait","goal":6,"start":["KeyM"],"required":["KeyI"],"tank":["KeyM","Comma","KeyL","KeyK","KeyJ","KeyN","KeyI","KeyU"],"zone":"caves",
  "terrain":{"KeyI":"cave"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyJ","KeyK","KeyL"],"loop":"pingpong","pathIndex":2,"at":"KeyJ"},
    {"type":"eel","mover":"chase","dir":"E","speed":1,"size":"big","prey":false,"cave":true,"wake":true,"at":"KeyI","path":[],"loop":"pingpong","pathIndex":0}]},
 {"id":"hermit","name":"Hermit","goal":7,"start":["KeyC"],"required":[],"zone":"caves",
  "terrain":{"KeyX":"algae","Space":"algae","KeyG":"algae","KeyS":"algae","Digit4":"algae","F4":"algae","Digit6":"algae","KeyY":"algae","Digit3":"algae","KeyW":"algae","KeyU":"algae","KeyJ":"algae","KeyK":"algae","Comma":"algae","KeyN":"cave","Digit5":"cave"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyB","KeyH","KeyN","KeyM"],"loop":"pingpong","pathIndex":2},
    {"type":"eel","mover":"chase","dir":"E","speed":1,"size":"big","prey":false,"cave":true,"wake":true,"at":"Digit5"}]},
 {"id":"mines","name":"Mines","goal":8,"start":["Comma"],"required":[],"zone":"caves",
  "terrain":{"KeyK":"algae","Space":"algae","AltRight":"algae","Semicolon":"algae","Digit9":"algae","Digit7":"algae","KeyY":"algae","ShiftRight":"algae","MetaRight":"algae","F8":"algae","Minus":"algae","KeyG":"algae","KeyB":"algae","KeyN":"algae","BracketLeft":"algae","F6":"algae","F7":"algae","BracketRight":"algae","Enter":"algae","KeyX":"algae","KeyC":"algae","KeyV":"algae","AltLeft":"algae","F5":"algae","Digit6":"algae","KeyT":"algae","ContextMenu":"algae","ControlRight":"algae","F9":"algae","Equal":"algae","KeyF":"algae","Backspace":"algae","Backslash":"algae","KeyU":"cave","KeyH":"cave","Digit0":"cave"},
  "creatures":[{"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":true,"wake":false,"at":"KeyH"},
    {"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":true,"wake":false,"at":"KeyU"},
    {"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":true,"wake":false,"at":"Digit0"},
    {"type":"fish","mover":"flee","dir":"E","speed":0.5,"size":"small","prey":true,"cave":false,"wake":false,"at":"KeyP"}]},
 {"id":"heard-not-seen","name":"Heard, not seen","goal":8,"start":["KeyX"],"required":[],"zone":"caves",
  "terrain":{"KeyS":"algae","KeyZ":"algae","AltLeft":"algae","Space":"algae","Digit4":"algae","Digit3":"algae","KeyW":"algae","KeyN":"algae","Digit6":"algae","KeyU":"algae","Digit7":"algae","KeyI":"algae","KeyM":"algae","KeyO":"algae","Comma":"algae","F4":"algae","KeyP":"algae","Semicolon":"algae","Period":"algae","KeyR":"algae","KeyK":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyB","KeyH","KeyG","KeyY","KeyT","KeyR","Digit5"],"loop":"loop","pathIndex":4}]},
 {"id":"blackout","name":"Blackout","goal":8,"start":["KeyZ"],"required":[],"zone":"caves",
  "terrain":{"ShiftLeft":"algae","KeyX":"algae","MetaLeft":"algae","AltLeft":"algae","CapsLock":"algae","KeyR":"algae","KeyC":"algae","Tab":"algae","F3":"algae","F4":"algae","KeyT":"algae","F5":"algae","Digit7":"algae","KeyY":"algae","F2":"algae","KeyV":"algae","KeyH":"algae","KeyB":"algae","F1":"algae","Escape":"algae","Digit2":"cave","Digit1":"cave","Backquote":"cave","KeyD":"cave"},
  "creatures":[{"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":true,"wake":false,"at":"Digit2"},
    {"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":true,"wake":false,"at":"Digit1"},
    {"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":true,"wake":false,"at":"Backquote"},
    {"type":"urchin","mover":"still","dir":"E","speed":0,"size":"big","prey":false,"cave":true,"wake":false,"at":"KeyD"},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyF","KeyG"],"loop":"pingpong","pathIndex":1}]},
 {"id":"two-loops","name":"Two loops","goal":8,"start":["Tab"],"required":[],"zone":"the-rim",
  "terrain":{"MetaLeft":"algae","Escape":"algae","KeyS":"algae","Digit2":"algae","Digit3":"algae","Digit4":"algae","KeyD":"algae","KeyT":"algae","KeyX":"algae","AltLeft":"algae","KeyV":"algae","KeyH":"algae","KeyB":"algae","Space":"algae","Digit6":"algae","Digit7":"algae","KeyU":"algae","F4":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyQ","KeyA","KeyW"],"loop":"loop","pathIndex":1},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyE","KeyR","KeyF","KeyG","KeyY"],"loop":"loop","pathIndex":4}]},
 {"id":"crab-clock","name":"Crab clock","goal":8,"start":["CapsLock"],"required":[],"zone":"the-rim",
  "terrain":{"MetaLeft":"algae","Digit3":"algae","KeyE":"algae","Space":"algae","Escape":"algae","KeyF":"algae","KeyC":"algae","ControlLeft":"algae","F1":"algae","Digit4":"algae","Digit5":"algae","Digit6":"algae","KeyY":"algae","KeyG":"algae","AltLeft":"rock","KeyW":"rock"},
  "creatures":[{"type":"crab","mover":"dir","dir":"E","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyQ"},
    {"type":"crab","mover":"dir","dir":"E","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyR"},
    {"type":"crab","mover":"dir","dir":"NW","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyD"}]},
 {"id":"big-tank","name":"Big tank","goal":10,"start":["Space"],"required":[],"zone":"the-rim",
  "terrain":{"KeyN":"algae","Period":"algae","MetaRight":"algae","KeyH":"algae","KeyU":"algae","KeyI":"algae","KeyP":"algae","MetaLeft":"algae","Slash":"algae","Minus":"algae","Equal":"algae","BracketRight":"algae","Enter":"algae","ShiftRight":"algae","F7":"algae","F8":"algae","KeyA":"algae","ShiftLeft":"algae","Digit7":"algae","KeyW":"algae","KeyD":"algae","KeyF":"algae","Digit3":"algae","Digit4":"algae","KeyR":"algae","F5":"algae","KeyT":"algae","KeyY":"algae","ContextMenu":"algae","ControlLeft":"algae","F9":"algae","F10":"algae","Backspace":"algae","Backslash":"algae","ControlRight":"algae","KeyQ":"algae","CapsLock":"algae","Digit6":"algae","Digit2":"algae","F2":"algae","F3":"algae","Digit5":"algae","KeyE":"cave","Digit0":"rock","Digit9":"rock","KeyK":"rock","KeyJ":"reef","Digit8":"reef"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyS","KeyX","KeyC","KeyV","KeyB","KeyG"],"loop":"loop","pathIndex":4},
    {"type":"eel","mover":"chase","dir":"E","speed":1,"size":"big","prey":false,"cave":true,"wake":true,"at":"KeyE"},
    {"type":"crab","mover":"dir","dir":"E","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyZ"},
    {"type":"fish","mover":"flee","dir":"E","speed":0.5,"size":"small","prey":true,"cave":false,"wake":false,"at":"BracketLeft"}]},
 {"id":"ctrl-z","name":"Ctrl+Z","goal":8,"start":["ControlLeft"],"required":["KeyZ"],"zone":"the-rim",
  "terrain":{"MetaLeft":"algae","KeyA":"algae","Space":"algae","Digit4":"algae","F1":"algae","Backquote":"algae","Tab":"algae","KeyF":"algae","KeyC":"algae","F2":"algae","KeyT":"algae","Digit6":"algae","F3":"algae"},
  "creatures":[{"type":"crab","mover":"dir","dir":"SE","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"Digit1"},
    {"type":"barracuda","mover":"dir","dir":"SW","speed":2,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyW"}]},
 {"id":"escape","name":"Escape","goal":8,"start":["Escape"],"required":["ShiftLeft"],"zone":"the-rim",
  "terrain":{"Digit1":"algae","KeyZ":"algae","ControlLeft":"algae","MetaLeft":"algae","KeyD":"algae","Digit3":"algae","F1":"algae","F3":"algae","Digit5":"algae","KeyC":"algae","AltLeft":"algae","Space":"algae","KeyF":"algae","Digit6":"algae","KeyY":"algae","KeyG":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyQ","KeyA","KeyS","KeyX"],"loop":"pingpong","pathIndex":1},
    {"type":"crab","mover":"dir","dir":"NW","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyW"}]},
 {"id":"enter","name":"Enter","goal":8,"start":["Enter"],"required":["Period"],"zone":"the-rim",
  "terrain":{"BracketRight":"algae","MetaRight":"algae","AltRight":"algae","Backspace":"algae","KeyK":"algae","Space":"algae","KeyJ":"algae","KeyN":"algae","ContextMenu":"algae","ControlRight":"algae","KeyP":"algae","Digit9":"algae","Digit0":"algae","KeyI":"algae","F9":"algae","F10":"algae"},
  "creatures":[{"type":"barracuda","mover":"dir","dir":"E","speed":2,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyO"},
    {"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyL","Comma","Period","Semicolon"],"loop":"loop","pathIndex":0}]},
 {"id":"f-row","name":"F-row","goal":8,"start":["F1"],"required":["F3","F4"],"zone":"the-rim",
  "terrain":{"KeyR":"algae","KeyW":"algae","KeyA":"algae","KeyZ":"algae","KeyX":"algae","F5":"algae","KeyY":"algae","KeyF":"algae","KeyG":"algae","KeyC":"algae","Backquote":"algae","F6":"algae","Digit8":"algae","KeyU":"algae","CapsLock":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["F2","F3","F4","Digit5"],"loop":"loop","pathIndex":3},
    {"type":"crab","mover":"dir","dir":"SW","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"KeyQ"}]},
 {"id":"alt-f4","name":"Alt+F4","goal":9,"start":["F4"],"required":["F4","AltRight"],"zone":"the-rim","finale":true,
  "terrain":{"Comma":"reef","KeyM":"reef","KeyG":"rock","KeyB":"algae","Digit4":"algae","KeyR":"algae","KeyF":"algae","Space":"algae","KeyK":"algae","KeyL":"algae","MetaRight":"algae","F5":"algae","KeyI":"algae","F6":"algae","F7":"algae","Digit9":"algae","Semicolon":"algae","Quote":"algae","ShiftRight":"algae","F3":"algae"},
  "creatures":[{"type":"shark","mover":"path","dir":"NE","speed":1,"size":"big","prey":false,"cave":false,"wake":false,"path":["KeyY","KeyU","Digit8","Digit7","Digit6"],"loop":"loop","pathIndex":2,"at":"KeyY"},
    {"type":"crab","mover":"dir","dir":"W","speed":0.5,"size":"small","prey":false,"cave":false,"wake":false,"at":"Slash","path":[],"loop":"pingpong","pathIndex":0}]}
];
